/**
 * Regenerate the boarding pass header banner.
 *
 *   pnpm tsx scripts/build-boarding-pass-banner.ts
 *
 * Emits lib/boarding-pass-banner.ts as a base64 data URI rather than having the
 * PDF read from public/ at request time: public/ is not reliably traced into a
 * Vercel serverless function, and a missing file would surface as a broken
 * boarding pass rather than a build error. Inlining costs a few tens of KB of
 * source and removes the failure mode entirely.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SOURCE = path.join(process.cwd(), "public/brand/hero-home.png");
const OUT = path.join(process.cwd(), "lib/boarding-pass-banner.ts");

// The pass renders the banner ~250pt wide in a ~120pt tall band. 900x300 keeps
// it crisp at print DPI without paying for pixels nobody sees.
const WIDTH = 900;
const HEIGHT = 300;

async function main() {
  const src = sharp(readFileSync(SOURCE));
  const { width = 0, height = 0 } = await src.metadata();

  // The illustration is 4096x1849 with the boat right of centre and a lot of
  // empty sky above it. Crop a band that keeps the boat and the waterline.
  const cropHeight = Math.round(width * (HEIGHT / WIDTH));
  const top = Math.max(0, Math.round(height * 0.34));

  const jpeg = await src
    .extract({
      left: 0,
      top: Math.min(top, Math.max(0, height - cropHeight)),
      width,
      height: Math.min(cropHeight, height),
    })
    .resize(WIDTH, HEIGHT, { fit: "cover" })
    .jpeg({ quality: 74, mozjpeg: true })
    .toBuffer();

  const dataUri = `data:image/jpeg;base64,${jpeg.toString("base64")}`;

  writeFileSync(
    OUT,
    `// Generated by scripts/build-boarding-pass-banner.ts — do not edit by hand.\n` +
      `// Source: public/brand/hero-home.png, cropped to ${WIDTH}x${HEIGHT}.\n\n` +
      `export const BOARDING_PASS_BANNER =\n  "${dataUri}";\n`,
  );

  console.log(
    `✓ ${path.relative(process.cwd(), OUT)} — ${WIDTH}x${HEIGHT}, ` +
      `${(jpeg.length / 1024).toFixed(1)} KB jpeg / ` +
      `${(dataUri.length / 1024).toFixed(1)} KB base64`,
  );
}

main();
