#!/usr/bin/env bash
#
# Deploy Gilijet to a fresh Ubuntu/Debian Linux box over SSH as root.
#
# Usage:
#   scripts/deploy.sh                       # uses default host 188.166.177.164
#   scripts/deploy.sh <host>                # custom IP / hostname
#   SSH_KEY=~/.ssh/id_ed25519 scripts/deploy.sh
#
# What it does:
#   1. Pings the box over SSH.
#   2. Installs Docker + rsync on first run (idempotent).
#   3. Generates ~/.gilijet/.env on the server (secrets persist across deploys).
#   4. rsyncs the repo into /opt/gilijet on the server.
#   5. `docker compose up -d --build` to (re)launch the app on port 80.
#   6. Tails health for ~30s and prints the URL.
#
set -euo pipefail

HOST="${1:-188.166.177.164}"
USER="${SSH_USER:-root}"
SSH_KEY_ARG=""
if [ -n "${SSH_KEY:-}" ]; then SSH_KEY_ARG="-i $SSH_KEY"; fi

REMOTE_DIR="/opt/gilijet"
REMOTE_ENV="/root/.gilijet/.env"
TARGET="${USER}@${HOST}"

# Allow customising the seed-on-first-boot via local env.
SEED_ON_START="${SEED_ON_START:-1}"

ssh_opts=(
  -o BatchMode=yes
  -o StrictHostKeyChecking=accept-new
  -o ConnectTimeout=10
)

remote() { ssh ${SSH_KEY_ARG} "${ssh_opts[@]}" "$TARGET" "$@"; }
remote_sh() { ssh ${SSH_KEY_ARG} "${ssh_opts[@]}" "$TARGET" bash -s; }

step() { printf "\n\033[1;36m▶ %s\033[0m\n" "$*"; }

# ---------- 1. preflight ----------
step "Checking SSH to ${TARGET}"
if ! remote 'echo ok' >/dev/null; then
  echo "ssh ${TARGET} failed. Verify the host is reachable and your key is loaded."
  echo "  Override key with: SSH_KEY=~/.ssh/id_ed25519 $0 ${HOST}"
  exit 1
fi
echo "✓ SSH ok"

# ---------- 2. install prereqs ----------
step "Installing Docker + rsync on remote (idempotent)"
remote_sh <<'REMOTE'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

if ! command -v docker >/dev/null 2>&1; then
  echo "Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg rsync ufw >/dev/null
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  systemctl enable --now docker
else
  apt-get install -y -qq rsync >/dev/null || true
fi

# Open port 80 if ufw is active
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  ufw allow 22/tcp  || true
  ufw allow 80/tcp  || true
fi

mkdir -p /opt/gilijet /root/.gilijet
REMOTE
echo "✓ Prereqs ok"

# ---------- 3. ensure secrets ----------
step "Ensuring server-side secrets at ${REMOTE_ENV}"
remote_sh <<REMOTE
set -euo pipefail
if [ ! -f "${REMOTE_ENV}" ]; then
  umask 077
  AUTH_SECRET="\$(openssl rand -base64 48 | tr -d '\\n=' | head -c 48)"
  QR_HMAC_SECRET="\$(openssl rand -hex 32)"
  POSTGRES_PASSWORD="\$(openssl rand -hex 24)"
  cat > "${REMOTE_ENV}" <<EOF
# Generated by scripts/deploy.sh on \$(date -Is). Do NOT commit.
AUTH_SECRET=\${AUTH_SECRET}
QR_HMAC_SECRET=\${QR_HMAC_SECRET}
POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
APP_BASE_URL=http://${HOST}
SEED_ON_START=${SEED_ON_START}
EOF
  echo "  wrote new ${REMOTE_ENV}"
else
  echo "  ${REMOTE_ENV} already present (keeping existing secrets)"
fi

# Reflect SEED_ON_START from the latest deploy invocation so the user can
# disable seeding on subsequent runs by re-running with SEED_ON_START=0.
sed -i "s/^SEED_ON_START=.*/SEED_ON_START=${SEED_ON_START}/" "${REMOTE_ENV}" || true
REMOTE
echo "✓ Secrets ok"

# ---------- 4. ship the code ----------
step "Rsyncing repo to ${TARGET}:${REMOTE_DIR}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
rsync -az --delete \
  --exclude=.git \
  --exclude=node_modules \
  --exclude=.next \
  --exclude=dist \
  --exclude=.env \
  --exclude='.env.*.local' \
  -e "ssh ${SSH_KEY_ARG} ${ssh_opts[*]}" \
  "${REPO_ROOT}/" "${TARGET}:${REMOTE_DIR}/"
echo "✓ Rsync done"

# ---------- 5. build + up ----------
step "Building and starting containers"
remote_sh <<REMOTE
set -euo pipefail
cd ${REMOTE_DIR}
ln -sf ${REMOTE_ENV} ${REMOTE_DIR}/.env
docker compose pull --ignore-buildable
docker compose up -d --build
docker image prune -f >/dev/null || true
REMOTE
echo "✓ docker compose up"

# ---------- 6. health ----------
step "Waiting for app health"
for i in $(seq 1 20); do
  if curl -fsS --max-time 3 "http://${HOST}/" >/dev/null 2>&1; then
    echo "✓ HTTP 200 from http://${HOST}/"
    echo
    echo "  Live → http://${HOST}/"
    echo "  Admin login → http://${HOST}/admin/login"
    if [ "${SEED_ON_START}" = "1" ]; then
      echo "  Seeded admin → admin@gilijet.local / changeme123 (CHANGE IT)"
    fi
    exit 0
  fi
  sleep 3
done

echo "⚠ App didn't return 200 within ~60s. Recent logs:"
remote "cd ${REMOTE_DIR} && docker compose logs --tail=80 app || true"
exit 1
