#!/usr/bin/env bash
#
# Deploy Gilifast to a fresh Ubuntu/Debian Linux box over SSH as root.
#
# Usage:
#   scripts/deploy.sh                       # uses default host 188.166.177.164
#   scripts/deploy.sh <host>                # custom IP / hostname
#   SSH_KEY=~/.ssh/id_ed25519 scripts/deploy.sh
#
# What it does:
#   1. Pings the box over SSH.
#   2. Installs Docker + rsync on first run (idempotent).
#   3. Generates ~/.gilifast/.env on the server (secrets persist across deploys).
#   4. rsyncs the repo into /opt/gilifast on the server.
#   5. `docker compose up -d --build` to (re)launch the app on port 80.
#   6. Tails health for ~30s and prints the URL.
#
set -euo pipefail

HOST="${1:-188.166.177.164}"
USER="${SSH_USER:-root}"
SSH_KEY_ARG=""
if [ -n "${SSH_KEY:-}" ]; then SSH_KEY_ARG="-i $SSH_KEY"; fi

REMOTE_DIR="/opt/gilifast"
REMOTE_ENV="/root/.gilifast/.env"
TARGET="${USER}@${HOST}"

# Off by default: entrypoint.sh runs prisma/seed.ts on every boot, not just the
# first, so leaving this on republished the sample operators after every deploy.
# Opt in explicitly with SEED_ON_START=1 when standing up a fresh environment.
SEED_ON_START="${SEED_ON_START:-0}"

ssh_opts=(
  -o BatchMode=yes
  -o StrictHostKeyChecking=accept-new
  -o ConnectTimeout=10
)

remote() { ssh ${SSH_KEY_ARG} "${ssh_opts[@]}" "$TARGET" "$@"; }
remote_sh() { ssh ${SSH_KEY_ARG} "${ssh_opts[@]}" "$TARGET" bash -s; }

step() { printf "\n\033[1;36m▶ %s\033[0m\n" "$*"; }

# ---------- 1. preflight ----------
step "Checking SSH to ${TARGET}"
if ! remote 'echo ok' >/dev/null; then
  echo "ssh ${TARGET} failed. Verify the host is reachable and your key is loaded."
  echo "  Override key with: SSH_KEY=~/.ssh/id_ed25519 $0 ${HOST}"
  exit 1
fi
echo "✓ SSH ok"

# ---------- 2. install prereqs ----------
step "Installing Docker + rsync on remote (idempotent)"
remote_sh <<'REMOTE'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

if ! command -v docker >/dev/null 2>&1; then
  echo "Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg rsync ufw >/dev/null
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  . /etc/os-release
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/${ID} ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  systemctl enable --now docker
else
  apt-get install -y -qq rsync >/dev/null || true
fi

# Open port 80 if ufw is active
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  ufw allow 22/tcp  || true
  ufw allow 80/tcp  || true
fi

# Pre-rename boxes keep their state at the old gilijet paths. Move it rather
# than starting fresh: /root/.gilijet/.env holds QR_HMAC_SECRET, and
# regenerating that invalidates the QR on every ticket already issued.
if [ -d /root/.gilijet ] && [ ! -d /root/.gilifast ]; then
  mv /root/.gilijet /root/.gilifast
  echo "  migrated /root/.gilijet -> /root/.gilifast (secrets preserved)"
fi
if [ -d /opt/gilijet ] && [ ! -d /opt/gilifast ]; then
  mv /opt/gilijet /opt/gilifast
  echo "  migrated /opt/gilijet -> /opt/gilifast"
fi
mkdir -p /opt/gilifast /root/.gilifast
REMOTE
echo "✓ Prereqs ok"

# ---------- 3. ensure secrets ----------
step "Ensuring server-side secrets at ${REMOTE_ENV}"
remote_sh <<REMOTE
set -euo pipefail
if [ ! -f "${REMOTE_ENV}" ]; then
  umask 077
  AUTH_SECRET="\$(openssl rand -base64 48 | tr -d '\\n=' | head -c 48)"
  QR_HMAC_SECRET="\$(openssl rand -hex 32)"
  POSTGRES_PASSWORD="\$(openssl rand -hex 24)"
  cat > "${REMOTE_ENV}" <<EOF
# Generated by scripts/deploy.sh on \$(date -Is). Do NOT commit.
AUTH_SECRET=\${AUTH_SECRET}
QR_HMAC_SECRET=\${QR_HMAC_SECRET}
POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
APP_BASE_URL=http://${HOST}
SEED_ON_START=${SEED_ON_START}
EOF
  echo "  wrote new ${REMOTE_ENV}"
else
  echo "  ${REMOTE_ENV} already present (keeping existing secrets)"
fi

# Append any key the app now needs that this env file predates, blank, so an
# existing box picks up new settings without losing its secrets. Blank values
# keep the corresponding integration in mock mode until they are filled in.
ensure_key() {
  grep -q "^\$1=" "${REMOTE_ENV}" || printf '%s=%s\n' "\$1" "\$2" >> "${REMOTE_ENV}"
}
# Generated, not blank: cron routes 401 without it.
ensure_key CRON_SECRET "\$(openssl rand -hex 32)"

# Set this to a domain whose A record points here and Caddy will serve HTTPS
# for it automatically. Left blank the box stays on plain HTTP, which Midtrans
# accepts but which sends payment notifications in the clear.
ensure_key APP_DOMAIN "${APP_DOMAIN:-}"

# APP_BASE_URL must follow the domain: it is what we hand Midtrans as the
# callback and notification base, so a stale http:// value here breaks payment
# silently.
domain="\$(grep '^APP_DOMAIN=' "${REMOTE_ENV}" | cut -d= -f2-)"
if [ -n "\$domain" ]; then
  sed -i "s|^APP_BASE_URL=.*|APP_BASE_URL=https://\$domain|" "${REMOTE_ENV}"
fi

ensure_key MIDTRANS_SERVER_KEY ""
ensure_key MIDTRANS_CLIENT_KEY ""
ensure_key MIDTRANS_MERCHANT_ID ""
ensure_key MIDTRANS_IS_PRODUCTION "false"
ensure_key PAYPAL_CLIENT_ID ""
ensure_key PAYPAL_CLIENT_SECRET ""
ensure_key PAYPAL_WEBHOOK_ID ""
ensure_key PAYPAL_IS_PRODUCTION "false"
ensure_key PAYPAL_PRESENTMENT_CURRENCY "USD"
ensure_key RESEND_API_KEY ""
ensure_key RESEND_FROM_EMAIL ""

# Reflect SEED_ON_START from the latest deploy invocation so the user can
# disable seeding on subsequent runs by re-running with SEED_ON_START=0.
sed -i "s/^SEED_ON_START=.*/SEED_ON_START=${SEED_ON_START}/" "${REMOTE_ENV}" || true
REMOTE
echo "✓ Secrets ok"

# Report which live integrations are actually wired, so a deploy never looks
# healthier than it is: blank keys mean the app silently runs in mock mode.
step "Checking live integrations on ${TARGET}"
remote_sh <<REMOTE
set -euo pipefail
check() {
  if grep -qE "^\$1=.+" "${REMOTE_ENV}"; then echo "  ✓ \$1"; else echo "  ✗ \$1 (mock)"; fi
}
check MIDTRANS_SERVER_KEY
check MIDTRANS_CLIENT_KEY
check PAYPAL_CLIENT_ID
check PAYPAL_CLIENT_SECRET
check CRON_SECRET
check RESEND_API_KEY
# Live PayPal keys sent to the sandbox host come back 401 invalid_client, and
# the app responds by quietly not offering PayPal — so the box looks configured
# while checkout has no backup gateway. Say so here instead.
if grep -qE '^PAYPAL_CLIENT_ID=.+' "${REMOTE_ENV}" &&
   ! grep -q '^PAYPAL_IS_PRODUCTION=true' "${REMOTE_ENV}"; then
  echo "  ! PayPal keys are set but PAYPAL_IS_PRODUCTION is not true — they will be"
  echo "    sent to the sandbox host. Run 'pnpm paypal:selftest' to see which host"
  echo "    accepts them."
fi
if grep -q '^MIDTRANS_IS_PRODUCTION=true' "${REMOTE_ENV}"; then
  base="\$(grep '^APP_BASE_URL=' "${REMOTE_ENV}" | cut -d= -f2-)"
  case "\$base" in
    https://*) ;;
    *) echo "  ! MIDTRANS_IS_PRODUCTION=true but APP_BASE_URL is \$base — notifications would travel in the clear" ;;
  esac
fi
REMOTE

# ---------- 4. ship the code ----------
step "Rsyncing repo to ${TARGET}:${REMOTE_DIR}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
rsync -az --delete \
  --exclude=.git \
  --exclude=node_modules \
  --exclude=.next \
  --exclude=dist \
  --exclude=.env \
  --exclude='.env.*.local' \
  -e "ssh ${SSH_KEY_ARG} ${ssh_opts[*]}" \
  "${REPO_ROOT}/" "${TARGET}:${REMOTE_DIR}/"
echo "✓ Rsync done"

# ---------- 5. build + up ----------
step "Building and starting containers"
remote_sh <<REMOTE
set -euo pipefail
cd ${REMOTE_DIR}
ln -sf ${REMOTE_ENV} ${REMOTE_DIR}/.env
docker compose pull --ignore-buildable
docker compose up -d --build
docker image prune -f >/dev/null || true
REMOTE
echo "✓ docker compose up"

# ---------- 6. health ----------
# Read back what the server settled on rather than assuming: the domain may have
# been set on a previous run, and probing the wrong scheme reports a false red.
APP_DOMAIN_REMOTE="$(remote "grep '^APP_DOMAIN=' ${REMOTE_ENV} | cut -d= -f2-" 2>/dev/null || true)"
if [ -n "${APP_DOMAIN_REMOTE}" ]; then
  BASE="https://${APP_DOMAIN_REMOTE}"
  echo "  APP_DOMAIN=${APP_DOMAIN_REMOTE} — Caddy will request a certificate on first request."
  echo "  This fails until the A record resolves to ${HOST}."
else
  BASE="http://${HOST}"
fi

step "Waiting for app health at ${BASE}"
for i in $(seq 1 20); do
  if curl -fsS --max-time 5 "${BASE}/" >/dev/null 2>&1; then
    echo "✓ HTTP 200 from ${BASE}/"
    echo
    echo "  Live → ${BASE}/"
    echo "  Admin login → ${BASE}/admin/login"
    if [ "${SEED_ON_START}" = "1" ]; then
      echo "  Seeded admin → admin@gilifast.local / changeme123 (CHANGE IT)"
    fi
    exit 0
  fi
  sleep 3
done

echo "⚠ App didn't return 200 within ~60s. Recent logs:"
remote "cd ${REMOTE_DIR} && docker compose logs --tail=80 app || true"
exit 1
